UPSTREAM: ath11k: Fix build warning without CONFIG_IPV6
drivers/net/wireless/ath/ath11k/mac.c:8175:13: error: ‘ath11k_mac_op_ipv6_changed’ defined but not used [-Werror=unused-function]
 static void ath11k_mac_op_ipv6_changed(struct ieee80211_hw *hw,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~

Wrap it with #ifdef block to fix this.

Fixes: c3c36bfe998b ("ath11k: support ARP and NS offload")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/20220411020843.10284-1-yuehaibing@huawei.com
(cherry picked from commit 67888630addeaa2ae1c04d8d020daccbd26d05d9)

BUG=b:232096343
TEST=emerge-herobrine chromeos-kernel-5_15; deploy and test basic WiFi
     functionality on herobrine device

Signed-off-by: Kevin Lund <kglund@google.com>
Change-Id: If0b8e30f995bca8691d016497b5aa403d6933403
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3651912
Reviewed-by: Abhishek Kumar <kuabhs@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>