FROMGIT: ASoC: SOF: amd: Fixed Build error
Add linux/module.h in acp-pci.c to solve the below dependency

All error/warnings (new ones prefixed by >>):

>> sound/soc/amd/acp/acp-pci.c:148:1: warning: data definition has no type or storage class
148 | MODULE_DEVICE_TABLE(pci, acp_pci_ids);
| ^~~~~~~~~~~~~~~~~~~
>> sound/soc/amd/acp/acp-pci.c:148:1: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE' [-Werror=implicit-int]
...

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Syed Saba Kareem<ssabakar@amd.com>
Link: https://lore.kernel.org/r/20220523112956.3087604-1-ssabakar@amd.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 803a1f7272797faa15a7879cdc70f9adaf3fdcba
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

BUG=b:232797503
TEST=Tested on Nipperkin

Signed-off-by: Syed Saba kareem <syed.sabakareem@amd.corp-partner.google.com>
Change-Id: Ida14a04043876423c29bdbde6e9ba9a974e8ced7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3679903
Commit-Queue: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Tested-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>