FIXUP: FROMLIST: sched: Add a coresched command line option
0-day reports:

bugs.c:(.init.text+0x2af): undefined reference to `coresched_select'
arch/x86/kernel/cpu/bugs.c:46:20: warning: 'coresched_select' used but never defined

coresched_select was for some reason declared inside '#ifdef CONFIG_SYSFS'.

BUG=b:147685035
TEST=build and boot for AMD device with 5.10 (grunt-kernelnext)

Change-Id: I83bcb8c2dabfdf6228824bd65b3eba07b2c70519
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3081801
Reviewed-by: Joel Fernandes <joelaf@google.com>
(cherry picked from commit 8de0f20fc5706b98bf0e0dce22009d548cfe7a3d)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3310999
Tested-by: Joel Fernandes <joelaf@google.com>
Commit-Queue: Joel Fernandes <joelaf@google.com>