FROMGIT: ASoC: amd: acp: Add new cpu dai's in machine driver
when using same cpu dai for 2 different dai links
below error is reported.
error: can't find BE for DAI ACPHS_VIRTUAL1.OUT

To avoid this error add new cpu dai.

Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Link: https://lore.kernel.org/r/20230109132104.1259479-2-venkataprasad.potturu@amd.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 099b923fc15d8faa91c5fc1b46cbc483d034f5dc
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/ for-next)

BUG=b:203820382
TEST=Tested on skyrim

Cq-Depend: chromium:4216082
Change-Id: I825d873b261bf3d873379a20e153ecd652fe6686
Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.corp-partner.google.com>
Signed-off-by: Baili Deng <bailideng@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4171242
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>