UPSTREAM: drm/amdgpu: Fix the code style warnings in gmc
Fix the code style warnings in gmc:
ERROR: space required after that ',' (ctx:VxV).

Signed-off-by: yipechai <YiPeng.Chai@amd.com>
Reviewed-by: Tao Zhou <tao.zhou1@amd.com>
Acked-by: Christian König <christian.koenig@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit d622c094f8fe7a77fda613964ffdd9a248d2550a)
Signed-off-by: Drew Davenport <ddavenport@chromium.org>

BUG=b:235993998
TEST=build test

Backported using forklift.py

Change-Id: Iebbe8970ab4c4eebf4d0f1b120a432437dcebd87