UPSTREAM: ASoC: rt5682s: use 'static' qualifier
Sparse reports the following warnings:

sound/soc/codecs/rt5682s.c:44:12: error: symbol 'rt5682s_supply_names'
was not declared. Should it be static?

sound/soc/codecs/rt5682s.c:74:26: error: symbol 'rt5682s_reg' was not
declared. Should it be static?

sound/soc/codecs/rt5682s.c:2841:30: error: symbol
'rt5682s_aif1_dai_ops' was not declared. Should it be static?

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20211025185933.144327-3-pierre-louis.bossart@linux.intel.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 49ba5e936e1512d4c7812d433048f8909234fca0)

BUG=b:223359324
TEST=boot to shell

Signed-off-by: Jiaxin Yu <jiaxin.yu@mediatek.corp-partner.google.com>
Change-Id: I69578f3afa3bb7a9708e21a5ae85f1735c7e450e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3566067
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Li-Yu Yu <aaronyu@google.com>
Commit-Queue: Li-Yu Yu <aaronyu@google.com>