UPSTREAM: rtw89: don't kick off TX DMA if failed to write skb
This is found by Smatch static checker warning:
	drivers/net/wireless/realtek/rtw89/mac80211.c:31 rtw89_ops_tx()
	error: uninitialized symbol 'qsel'.

The warning is because 'qsel' isn't filled by rtw89_core_tx_write() due to
failed to write. The way to fix it is to avoid kicking off TX DMA, so add
'return' to the failure case.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20211201093816.13806-1-pkshih@realtek.com
(cherry picked from commit a58fdb7c843a37d6598204c6513961feefdadc6a)

BUG=b:238769358,b:178542556
TEST=suite:wifi_matfunc, suite:wifi_perf, and coex tests

Signed-off-by: Zong-Zhe Yang <kevin_yang@realtek.com>
Change-Id: Ibb3bfd4a859dc78ffad87ff6e4e28277d5c21fd7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3372480
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Matthew Wang <matthewmwang@chromium.org>
Tested-by: Matthew Wang <matthewmwang@chromium.org>
Commit-Queue: Matthew Wang <matthewmwang@chromium.org>
(cherry picked from commit ee0dbaf3a80c19eccba2131d2fbdfdecf78941c6)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3762214
Reviewed-by: Sean Paul <sean@poorly.run>
Commit-Queue: Arowa Suliman <arowa@chromium.org>
Reviewed-by: Arowa Suliman <arowa@chromium.org>
Tested-by: Arowa Suliman <arowa@chromium.org>