x86/kvm: Add kvm_adjust_suspend_time for correcting
While compiling after picking 29c23cf, an error occur because
`kvm_adjust_suspend_time` was missing.

arch/x86/kvm/x86.c:9810:13: error: unused function 'kvm_adjust_suspend_time' [-Werror,-Wunused-function]
 9810 | static void kvm_adjust_suspend_time(struct kvm_vcpu *vcpu)
      |             ^~~~~~~~~~~~~~~~~~~~~~~

Thus this commit adds back the missing kvm_adjust_suspend_time and
its matched parameter `vm_adjust_suspend_time`.

Signed-off-by: crrashh1542 <kotsuki@crrashh.com>