CHROMIUM: media: camx: cam_icp: Fix indentation
cam_icp_hw_mgr.c:1850:17: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]

BUG=none
TEST=make C=1 W=1
UPSTREAM-TASK=b:274966069

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: I74e0f86ef97d649abc86bab51ccc2555bdd45847
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4921752
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
(cherry picked from commit 31918420e54a7512f374d84c1a79fdec50f47db4)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4926210