FIXUP: drm/evdi: Add atomic evdi drm module
0-day reports:

drivers/gpu/drm/evdi/evdi_modeset.c:387:44: error:
	'evdi_cursor_helper_funcs' defined but not used

Looks like the user(s) of this datastructure were at some point removed.
Drop the structure as well. After that, we get:

drivers/gpu/drm/evdi/evdi_modeset.c:309:13: error:
	‘evdi_cursor_atomic_update’ defined but not used

so that function can be removed as well. Then:

drivers/gpu/drm/evdi/evdi_modeset.c:300:13: error:
	‘evdi_cursor_atomic_get_rect’ defined but not used

so there is one more function to remove.

BUG=b:204816062
TEST=make allmodconfig; make W=1 drivers/gpu/drm/evdi/

Change-Id: Ibe2d336d1540d95f870fe42ca5e53997dc68a528
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3338278
Reviewed-by: Anand Mistry <amistry@chromium.org>
Commit-Queue: Anand Mistry <amistry@chromium.org>