UPSTREAM: KVM: arm64: nvhe: Fix build with profile optimization
Kernel build with clang and KCFLAGS=-fprofile-sample-use=<profile> fails with:

error: arch/arm64/kvm/hyp/nvhe/kvm_nvhe.tmp.o: Unexpected SHT_REL
section ".rel.llvm.call-graph-profile"

Starting from 13.0.0 llvm can generate SHT_REL section, see
https://reviews.llvm.org/rGca3bdb57fa1ac98b711a735de048c12b5fdd8086.
gen-hyprel does not support SHT_REL relocation section.

Filter out profile use flags to fix the build with profile optimization.

Signed-off-by: Denis Nikitin <denik@chromium.org>
Signed-off-by: Marc Zyngier <maz@kernel.org>
Link: https://lore.kernel.org/r/20221014184532.3153551-1-denik@chromium.org
(cherry picked from commit bde971a83bbff78561458ded236605a365411b87)

BUG=b:245629081
TEST=USE="kernel_afdo kern_arm_afdo" emerge-trogdor chromeos-kernel-5_15

Signed-off-by: Denis Nikitin <denik@chromium.org>
Change-Id: Ib6c30136d8e552fc1ec4dd40a4b4704e4851a33a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3882253
Reviewed-by: Sean Paul <sean@poorly.run>
Reviewed-by: Guenter Roeck <groeck@chromium.org>