FIXUP: BACKPORT: FROMLIST: drm/i915: Switch to fdinfo helper
0-day warning:
>> drivers/gpu/drm/i915/i915_drm_client.h:63:36: error: declaration
   of 'struct drm_printer' will not be visible outside of this function
>> drivers/gpu/drm/i915/i915_drm_client.h:63:59: error: declaration
   of 'struct drm_file' will not be visible outside of this function

Declare missing structs.

BUG=b:278115755,b:227610040
TEST=Boot wormdingler, check /proc/$pid/fdinfo/$fd
UPSTREAM-TASK=b:284166503

Change-Id: I27edd34c264916b6772e00c34d3f92c4ce8d0cfc
Signed-off-by: Aashish Sharma <shraash@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4644408
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>