FROMGIT: soundwire: qcom: use __maybe_unused for swrm_runtime_resume()
swrm_runtime_resume() would not be defined when CONFIG_PM=n

This causes below build failure
drivers/soundwire/qcom.c:1460:12: error: 'swrm_runtime_resume' defined
but not used [-Werror=unused-function]

Mark the resume swrm_runtime_resume() with  __maybe_unused attribute.

Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Link: https://lore.kernel.org/r/20220303110321.23666-1-srinivas.kandagatla@linaro.org
[redo commit title and log]
Signed-off-by: Vinod Koul <vkoul@kernel.org>
(cherry picked from commit 266fa94673d325f489f74d0a9a12024a7f1ee49c
 https://git.kernel.org/pub/scm/linux/kernel/git/vkoul/soundwire.git/ next)

BUG=b:177043625
TEST=emerge-herobrine sys-kernel/chromeos-kernel-5_15

Change-Id: I65a2123313d610006b8dbc0731a3092a6ffc5aa3
Signed-off-by: Srinivasa Rao Mandadapu <quic_srivasam@quicinc.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3517032
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Tested-by: Judy Hsiao <judyhsiao@google.com>
Commit-Queue: Judy Hsiao <judyhsiao@google.com>
Reviewed-by: Judy Hsiao <judyhsiao@google.com>