ext4: Fix an compilance error after merging from AOSP
In the commit d21c229, `ext4_set_bits` were renamed to `mb_set_bits` for further
changes. However, while merging from AOSP upstream, I retained the `ext4_set_bits`
from upstream by mistake, which causes the error below:

fs/ext4/mballoc.c:1178:3: error: implicit declaration of function 'ext4_set_bits' [-Werror,-Wimplicit-function-declaration]
 1178 |                 ext4_set_bits(buddy, 0, count);
      |                 ^

Therefore, this commit brings back the previously replaced `mb_set_bits`.

Signed-off-by: crrashh1542 <kotsuki@crrashh.com>