UPSTREAM: thunderbolt: Fix -Wrestrict warning
gcc-11 warns when building with W=1:

drivers/thunderbolt/xdomain.c: In function 'modalias_show':
drivers/thunderbolt/xdomain.c:733:16: error: 'sprintf' argument 3 overlaps destination object 'buf' [-Werror=restrict]
  733 |         return sprintf(buf, "%s\n", buf);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/thunderbolt/xdomain.c:727:36: note: destination object referenced by 'restrict'-qualified argument 1 was declared here
  727 |                              char *buf)
      |                              ~~~~~~^~~

There is no need for the sprintf() here when a strcat() does
the same thing.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>
(cherry picked from commit 0a0624a26f9ceb8aae16882d87dc3b12f17f4a49
 https://git.kernel.org/pub/scm/linux/kernel/git/westeri/thunderbolt.git next)

BUG=b:242112030
TEST=emerge-rex sys-kernel/chromeos-kernel-5_15

Signed-off-by: Narasimha Rao Rayala <narasimha.rao.rayala@intel.com>
Change-Id: I28a979bcd629a151b2a97ff66219103d3aadfc58
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3881657
Commit-Queue: Prashant Malani <pmalani@chromium.org>
Reviewed-by: Prashant Malani <pmalani@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>