UPSTREAM: drm: import DMA_BUF module namespace
Today's -next fails building arm64 defconfig as follows:

ERROR: modpost: module drm_cma_helper uses symbol dma_buf_vunmap from
 namespace DMA_BUF, but does not import it.
ERROR: modpost: module drm_cma_helper uses symbol dma_buf_vmap from
 namespace DMA_BUF, but does not import it.

Fix this by importing DMA_BUF namespace into drm_cma_helper.ko. Also
fix the problem with drm_shmem_helper.ko.

Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
Fixes: 4b2b5e142ff4 ("drm: Move GEM memory managers into modules")
Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
Link: https://patchwork.freedesktop.org/patch/msgid/20211027212506.3418521-1-marcel@ziswiler.com
(cherry picked from commit 675053115e4e809643e12ca817dc9147562a70d6)

BUG=b:215432805
TEST=Future patches easier to pick

Signed-off-by: Douglas Anderson <dianders@chromium.org>
Change-Id: Ieb22dc9beb43ec1b6f30d6969704fb6a7ba4a60e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3470725
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Reviewed-by: Drew Davenport <ddavenport@chromium.org>